In [2]:
import pandas as pd 
df = pd.read_csv("brennan_johnson_stats.csv")

df.columns = df.iloc[0]  
df = df[1:].reset_index(drop=True)  

df.columns = df.columns.str.strip()
df.drop("Matches", axis=1, inplace=True)

df.to_csv("brennan_johnson_stats_cleaned.csv")

df.head()

,Season,Age,Squad,Country,Comp,MP,Starts,Min,90s,Gls,...,Gls,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG
0,2019-2020,18,Nott'ham Forest,eng ENG,2. Championship,4,2,110,1.2,0,...,0.00,0.00,0.00,0.00,0.00,0.08,0.05,0.13,0.08,0.13
1,2019-2020,18,Nott'ham Forest,eng ENG,EFL Cup,3,2,172,1.9,0,...,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN
2,2019-2020,18,Nott'ham Forest,eng ENG,FA Cup,1,1,80,0.9,0,...,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN
3,2020-2021,19,Nott'ham Forest,eng ENG,2. Championship,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-2021,19,Lincoln City,eng ENG,FA Cup,2,2,180,2.0,1,...,0.50,0.00,0.50,0.50,0.50,NaN,NaN,NaN,NaN,NaN

In [401]:
print(df.columns)

Index(['Season', 'Age', 'Squad', 'Country', 'Comp', 'MP', 'Starts', 'Min',
       '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'xG',
       'npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP', 'PrgR', 'Gls', 'Ast', 'G+A',
       'G-PK', 'G+A-PK', 'xG', 'xAG', 'xG+xAG', 'npxG', 'npxG+xAG'],
      dtype='object', name=0)

In [402]:
print( df.info())

print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 34 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Season    30 non-null     object
 1   Age       30 non-null     object
 2   Squad     30 non-null     object
 3   Country   20 non-null     object
 4   Comp      25 non-null     object
 5   MP        31 non-null     object
 6   Starts    31 non-null     object
 7   Min       29 non-null     object
 8   90s       29 non-null     object
 9   Gls       29 non-null     object
 10  Ast       29 non-null     object
 11  G+A       29 non-null     object
 12  G-PK      29 non-null     object
 13  PK        29 non-null     object
 14  PKatt     29 non-null     object
 15  CrdY      29 non-null     object
 16  CrdR      29 non-null     object
 17  xG        14 non-null     object
 18  npxG      14 non-null     object
 19  xAG       14 non-null     object
 20  npxG+xAG  14 non-null     object
 21  PrgC      14 non-null     object
 22  PrgP      14 non-null     object
 23  PrgR      14 non-null     object
 24  Gls       29 non-null     object
 25  Ast       29 non-null     object
 26  G+A       29 non-null     object
 27  G-PK      29 non-null     object
 28  G+A-PK    29 non-null     object
 29  xG        14 non-null     object
 30  xAG       14 non-null     object
 31  xG+xAG    14 non-null     object
 32  npxG      14 non-null     object
 33  npxG+xAG  14 non-null     object
dtypes: object(34)
memory usage: 8.6+ KB
None
0          Season Age            Squad  Country    Comp  MP Starts   Min  \
count          30  30               30       20      25  31     31    29
unique         16  16               13        2      10  21     19    27
top     2024-2025  23  Nott'ham Forest  eng ENG  FA Cup   1      2  3307
freq            4   4               12       19       6   4      4     2

0        90s Gls  ...   Gls   Ast   G+A  G-PK G+A-PK    xG   xAG xG+xAG  npxG  \
count     29  29  ...    29    29    29    29     29    14    14     14    14
unique    27  15  ...    17    14    19    17     19    13    11     13    13
top     36.7   0  ...  0.00  0.00  0.00  0.00   0.00  0.45  0.20   0.72  0.45
freq       2   7  ...     7    14     7     7      7     2     2      2     2

0      npxG+xAG
count        14
unique       13
top        0.72
freq          2

[4 rows x 34 columns]

In [403]:
df = df.iloc[:20]  # الاحتفاظ بالصفوف من 0 إلى 19 فقط
df = df.reset_index(drop=True)



print(df[df.columns[0]])

0     2019-2020
1     2019-2020
2     2019-2020
3     2020-2021
4     2020-2021
5     2020-2021
6     2021-2022
7     2021-2022
8     2021-2022
9     2022-2023
10    2022-2023
11    2022-2023
12    2023-2024
13    2023-2024
14    2023-2024
15    2023-2024
16    2024-2025
17    2024-2025
18    2024-2025
19    2024-2025
Name: Season, dtype: object

In [404]:

df.drop(df[df["MP"] == '0'].index, inplace=True)


df

,Season,Age,Squad,Country,Comp,MP,Starts,Min,90s,Gls,...,Gls,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG
0,2019-2020,18,Nott'ham Forest,eng ENG,2. Championship,4,2,110,1.2,0,...,0.00,0.00,0.00,0.00,0.00,0.08,0.05,0.13,0.08,0.13
1,2019-2020,18,Nott'ham Forest,eng ENG,EFL Cup,3,2,172,1.9,0,...,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN
2,2019-2020,18,Nott'ham Forest,eng ENG,FA Cup,1,1,80,0.9,0,...,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN
4,2020-2021,19,Lincoln City,eng ENG,FA Cup,2,2,180,2.0,1,...,0.50,0.00,0.50,0.50,0.50,NaN,NaN,NaN,NaN,NaN
5,2020-2021,19,Lincoln City,eng ENG,3. League One,40,38,3307,36.7,10,...,0.27,0.16,0.44,0.24,0.41,NaN,NaN,NaN,NaN,NaN
6,2021-2022,20,Nott'ham Forest,eng ENG,2. Championship,46,44,3898,43.3,16,...,0.37,0.23,0.60,0.30,0.53,0.30,0.20,0.50,0.24,0.44
8,2021-2022,20,Nott'ham Forest,eng ENG,FA Cup,4,4,357,4.0,1,...,0.25,0.00,0.25,0.25,0.25,NaN,NaN,NaN,NaN,NaN
9,2022-2023,21,Nott'ham Forest,eng ENG,EFL Cup,5,4,339,3.8,2,...,0.53,0.00,0.53,0.27,0.27,NaN,NaN,NaN,NaN,NaN
10,2022-2023,21,Nott'ham Forest,eng ENG,FA Cup,1,0,23,0.3,0,...,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN
11,2022-2023,21,Nott'ham Forest,eng ENG,1. Premier League,38,33,2934,32.6,8,...,0.25,0.09,0.34,0.21,0.31,0.26,0.10,0.36,0.19,0.29
12,2023-2024,22,Nott'ham Forest,eng ENG,EFL Cup,1,0,19,0.2,0,...,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN
13,2023-2024,22,Tottenham,eng ENG,FA Cup,2,2,153,1.7,0,...,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN
14,2023-2024,22,Tottenham,eng ENG,1. Premier League,32,23,2085,23.2,5,...,0.22,0.43,0.65,0.22,0.65,0.44,0.35,0.79,0.44,0.79
15,2023-2024,22,Nott'ham Forest,eng ENG,1. Premier League,3,3,237,2.6,0,...,0.00,0.00,0.00,0.00,0.00,0.12,0.08,0.21,0.12,0.21
16,2024-2025,23,Tottenham,eng ENG,EFL Cup,4,1,217,2.4,1,...,0.41,0.00,0.41,0.41,0.41,NaN,NaN,NaN,NaN,NaN
17,2024-2025,23,Tottenham,NaN,2. Europa Lg,6,4,288,3.2,3,...,0.94,0.31,1.25,0.94,1.25,0.45,0.27,0.72,0.45,0.72
18,2024-2025,23,Tottenham,eng ENG,FA Cup,1,1,120,1.3,1,...,0.75,0.00,0.75,0.75,0.75,NaN,NaN,NaN,NaN,NaN
19,2024-2025,23,Tottenham,eng ENG,1. Premier League,21,16,1492,16.6,7,...,0.42,0.12,0.54,0.42,0.54,0.48,0.08,0.56,0.48,0.56

In [405]:
df.columns = ['season', 'age', 'squad', 'country', 'comp', 'games_played','starts', 'mins','90s', 'goals', 'assists', 'g+a', 'non_pens_goals', 'pens', 'pkatt','yellow_card' ,"red_card","xg",'npxg','xa','npxg+xa','progC','progP','progR', 'goals_per90', 'assists_per90', 'goals_and_assists_per90', 'non_pens_goals_per90', 'goals_assists_non_pens_per90','xg_per90', 'xa_per90', 'xg_xa_per90', 'npxg_per90', 'npxg_xa_per90']

df.drop(columns=["90s",'pkatt'], inplace=True)



print(df.columns)

df.info()

Index(['season', 'age', 'squad', 'country', 'comp', 'games_played', 'starts',
       'mins', 'goals', 'assists', 'g+a', 'non_pens_goals', 'pens',
       'yellow_card', 'red_card', 'xg', 'npxg', 'xa', 'npxg+xa', 'progC',
       'progP', 'progR', 'goals_per90', 'assists_per90',
       'goals_and_assists_per90', 'non_pens_goals_per90',
       'goals_assists_non_pens_per90', 'xg_per90', 'xa_per90', 'xg_xa_per90',
       'npxg_per90', 'npxg_xa_per90'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 0 to 19
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   season                        18 non-null     object
 1   age                           18 non-null     object
 2   squad                         18 non-null     object
 3   country                       17 non-null     object
 4   comp                          18 non-null     object
 5   games_played                  18 non-null     object
 6   starts                        18 non-null     object
 7   mins                          18 non-null     object
 8   goals                         18 non-null     object
 9   assists                       18 non-null     object
 10  g+a                           18 non-null     object
 11  non_pens_goals                18 non-null     object
 12  pens                          18 non-null     object
 13  yellow_card                   18 non-null     object
 14  red_card                      18 non-null     object
 15  xg                            7 non-null      object
 16  npxg                          7 non-null      object
 17  xa                            7 non-null      object
 18  npxg+xa                       7 non-null      object
 19  progC                         7 non-null      object
 20  progP                         7 non-null      object
 21  progR                         7 non-null      object
 22  goals_per90                   18 non-null     object
 23  assists_per90                 18 non-null     object
 24  goals_and_assists_per90       18 non-null     object
 25  non_pens_goals_per90          18 non-null     object
 26  goals_assists_non_pens_per90  18 non-null     object
 27  xg_per90                      7 non-null      object
 28  xa_per90                      7 non-null      object
 29  xg_xa_per90                   7 non-null      object
 30  npxg_per90                    7 non-null      object
 31  npxg_xa_per90                 7 non-null      object
dtypes: object(32)
memory usage: 4.6+ KB

In [406]:

df['season'] = df['season'].astype(str)
df['age'] = df['age'].astype('Int8')   
df['games_played'] = df['games_played'].astype(float)
df['starts'] = df['starts'].astype(float)
df['mins'] = df['mins'].astype(float)
df['goals'] = df['goals'].astype(float)
df['assists'] = df['assists'].astype(float)
df['g+a'] = df['g+a'].astype(float)
df['non_pens_goals'] = df['non_pens_goals'].astype(float)
df['pens'] = df['pens'].astype(float)
df['yellow_card'] = df['yellow_card'].astype(float)
df['red_card'] = df['red_card'].astype(float)
df['xg'] = df['xg'].astype(float)
df['npxg'] = df['npxg'].astype(float)
df['xa'] = df['xa'].astype(float)
df['npxg+xa'] = df['npxg+xa'].astype(float)
df['progC'] = df['progC'].astype(float)
df['progP'] = df['progP'].astype(float)
df['progR'] = df['progR'].astype(float)
df['goals_per90'] = df['goals_per90'].astype(float)
df['assists_per90'] = df['assists_per90'].astype(float)
df['goals_and_assists_per90'] = df['goals_and_assists_per90'].astype(float)
df['non_pens_goals_per90'] = df['non_pens_goals_per90'].astype(float)
df['goals_assists_non_pens_per90'] = df['goals_assists_non_pens_per90'].astype(float)
df['xg_per90'] = df['xg_per90'].astype(float)
df['xa_per90'] = df['xa_per90'].astype(float)
df['xg_xa_per90'] = df['xg_xa_per90'].astype(float)
df['npxg_per90'] = df['npxg_per90'].astype(float)
df['npxg_xa_per90'] = df['npxg_xa_per90'].astype(float)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 0 to 19
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   season                        18 non-null     object
 1   age                           18 non-null     Int8
 2   squad                         18 non-null     object
 3   country                       17 non-null     object
 4   comp                          18 non-null     object
 5   games_played                  18 non-null     float64
 6   starts                        18 non-null     float64
 7   mins                          18 non-null     float64
 8   goals                         18 non-null     float64
 9   assists                       18 non-null     float64
 10  g+a                           18 non-null     float64
 11  non_pens_goals                18 non-null     float64
 12  pens                          18 non-null     float64
 13  yellow_card                   18 non-null     float64
 14  red_card                      18 non-null     float64
 15  xg                            7 non-null      float64
 16  npxg                          7 non-null      float64
 17  xa                            7 non-null      float64
 18  npxg+xa                       7 non-null      float64
 19  progC                         7 non-null      float64
 20  progP                         7 non-null      float64
 21  progR                         7 non-null      float64
 22  goals_per90                   18 non-null     float64
 23  assists_per90                 18 non-null     float64
 24  goals_and_assists_per90       18 non-null     float64
 25  non_pens_goals_per90          18 non-null     float64
 26  goals_assists_non_pens_per90  18 non-null     float64
 27  xg_per90                      7 non-null      float64
 28  xa_per90                      7 non-null      float64
 29  xg_xa_per90                   7 non-null      float64
 30  npxg_per90                    7 non-null      float64
 31  npxg_xa_per90                 7 non-null      float64
dtypes: Int8(1), float64(27), object(4)
memory usage: 4.5+ KB

In [407]:
df['npxg'].fillna(df['xg'], inplace=True)

df['xa_per90'] = df['xa'] / df['mins'] * 90

df.fillna(df.select_dtypes(include=['object']).mode().iloc[0], inplace=True)


df.loc[df['games_played'] > 5, df.select_dtypes(include=['float']).columns] = \
df.loc[df['games_played'] > 5, df.select_dtypes(include=['float']).columns].fillna(df.select_dtypes(include=['float']).std())

df.fillna(0.7, inplace=True)



df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 0 to 19
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   season                        18 non-null     object
 1   age                           18 non-null     Int8
 2   squad                         18 non-null     object
 3   country                       18 non-null     object
 4   comp                          18 non-null     object
 5   games_played                  18 non-null     float64
 6   starts                        18 non-null     float64
 7   mins                          18 non-null     float64
 8   goals                         18 non-null     float64
 9   assists                       18 non-null     float64
 10  g+a                           18 non-null     float64
 11  non_pens_goals                18 non-null     float64
 12  pens                          18 non-null     float64
 13  yellow_card                   18 non-null     float64
 14  red_card                      18 non-null     float64
 15  xg                            18 non-null     float64
 16  npxg                          18 non-null     float64
 17  xa                            18 non-null     float64
 18  npxg+xa                       18 non-null     float64
 19  progC                         18 non-null     float64
 20  progP                         18 non-null     float64
 21  progR                         18 non-null     float64
 22  goals_per90                   18 non-null     float64
 23  assists_per90                 18 non-null     float64
 24  goals_and_assists_per90       18 non-null     float64
 25  non_pens_goals_per90          18 non-null     float64
 26  goals_assists_non_pens_per90  18 non-null     float64
 27  xg_per90                      18 non-null     float64
 28  xa_per90                      18 non-null     float64
 29  xg_xa_per90                   18 non-null     float64
 30  npxg_per90                    18 non-null     float64
 31  npxg_xa_per90                 18 non-null     float64
dtypes: Int8(1), float64(27), object(4)
memory usage: 4.5+ KB

C:\Users\hp\AppData\Local\Temp\ipykernel_23908\1210752909.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['npxg'].fillna(df['xg'], inplace=True)

In [408]:
print(df.duplicated().sum())

0

In [409]:
df.to_csv("brennan_johnson_cleaned.csv", index=False)